name: Release

on:
  push:
    paths:
      - "plugin.yaml"

permissions:
  contents: write

jobs:
  check-version:
    name: "Check version"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      next_version: ${{ steps.next-version.outputs.next_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get new version
        id: next-version
        run: echo "next_version=$(git diff HEAD^ HEAD --diff-filter=ACMRT -- plugin.yaml -- -U0 | awk '/^\+\s*version:/ {print $2}' | grep -Po '\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: [check-version]
    if: ${{ needs.check-version.outputs.next_version != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.0'
      - run: git tag v${{ needs.check-version.outputs.next_version }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f=goreleaser.yml --rm-dist --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v${{ needs.check-version.outputs.next_version }}
